name:                polyest
version:             0.1.0.0
github:              "rod-lin/polyest"
license:             MIT
author:              "rodlin"
maintainer:          "im.rod@outlook.com"
copyright:           "2019 rodlin"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/polyest#readme>

dependencies:
- base >= 4.7 && < 5
- integration == 0.2.1

default-extensions:
- MultiParamTypeClasses
- QuantifiedConstraints
- ScopedTypeVariables
- FlexibleInstances
- FlexibleContexts
- KindSignatures
- DataKinds
- GADTs

library:
  source-dirs: src

executables:
  polyest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polyest
